// flow-typed signature: 565b1784ed03abc2b2bbdf116dc38cd0
// flow-typed version: <<STUB>>/keythereum_v^1.0.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keythereum'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keythereum' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keythereum/exports' {
  declare module.exports: any;
}

declare module 'keythereum/lib/scrypt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keythereum/exports.js' {
  declare module.exports: $Exports<'keythereum/exports'>;
}
declare module 'keythereum/index' {
  declare module.exports: $Exports<'keythereum'>;
}
declare module 'keythereum/index.js' {
  declare module.exports: $Exports<'keythereum'>;
}
declare module 'keythereum/lib/scrypt.js' {
  declare module.exports: $Exports<'keythereum/lib/scrypt'>;
}
