// flow-typed signature: 2bb1da4fa38cd5b0e1f8fa9aa8341798
// flow-typed version: <<STUB>>/next-optimized-images_v^1.4.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-optimized-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-optimized-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-optimized-images/svg-runtime-generator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-optimized-images/index' {
  declare module.exports: $Exports<'next-optimized-images'>;
}
declare module 'next-optimized-images/index.js' {
  declare module.exports: $Exports<'next-optimized-images'>;
}
declare module 'next-optimized-images/svg-runtime-generator.js' {
  declare module.exports: $Exports<'next-optimized-images/svg-runtime-generator'>;
}
