// flow-typed signature: 6651c6d121f678cc30e5130fce48c009
// flow-typed version: <<STUB>>/next-images_v^1.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-images/index' {
  declare module.exports: $Exports<'next-images'>;
}
declare module 'next-images/index.js' {
  declare module.exports: $Exports<'next-images'>;
}
