// flow-typed signature: bd6fdee0bd9889408e230a6b776e8820
// flow-typed version: <<STUB>>/next-fonts_v^0.10.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-fonts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-fonts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-fonts/index' {
  declare module.exports: $Exports<'next-fonts'>;
}
declare module 'next-fonts/index.js' {
  declare module.exports: $Exports<'next-fonts'>;
}
