// flow-typed signature: 33680c144e50036607c6cabd6c84813b
// flow-typed version: <<STUB>>/react-c3js_v^0.1.20/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-c3js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-c3js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-c3js/react-c3js' {
  declare module.exports: any;
}

declare module 'react-c3js/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-c3js/react-c3js.js' {
  declare module.exports: $Exports<'react-c3js/react-c3js'>;
}
declare module 'react-c3js/src/index.js' {
  declare module.exports: $Exports<'react-c3js/src/index'>;
}
